# Generated by Django 5.2.1 on 2025-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите Телеграм chat-id', max_length=50, null=True, verbose_name='Телеграм chat-id'),
        ),
    ]
