# Generated by Django 5.2.1 on 2025-06-22 11:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Введите место, в котором необходимо выполнять привычку', max_length=255, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(help_text='Введите время, когда необходимо выполнять привычку', verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=255, verbose_name='Действие, которое представляет собой привычка')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Отметьте, является ли эта привычка приятной', verbose_name='Признак приятной привычки')),
                ('periodicity_days', models.PositiveSmallIntegerField(default=1, help_text='Интервал в днях между выполнениями привычки (1-7 дней)', validators=[django.core.validators.MinValueValidator(1, message='Периодичность не может быть меньше 1 дня'), django.core.validators.MaxValueValidator(7, message='Нельзя выполнять привычку реже чем 1 раз в 7 дней')], verbose_name='Периодичность (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Чем пользователь должен себя вознаградить после выполнения', max_length=255, null=True, verbose_name='Вознаграждение после выполнения')),
                ('time_to_complete', models.PositiveIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки (1-120 минут)', validators=[django.core.validators.MinValueValidator(1, message='Время выполнения должно быть не менее 1 минуты'), django.core.validators.MaxValueValidator(120, message='Время выполнения не должно превышать 120 минут')], verbose_name='Время на выполнение (в минутах)')),
                ('is_public', models.BooleanField(default=False, help_text='Отметьте, можно ли публиковать привычки в общий доступ', verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой привычкой. Указывать только для полезных привычек', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_habit', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь — создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
