# Generated by Django 5.2.1 on 2025-06-18 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_habits_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Интервал в днях между выполнениями привычки (1-7 дней)', validators=[django.core.validators.MinValueValidator(1, message='Периодичность не может быть меньше 1 дня'), django.core.validators.MaxValueValidator(7, message='Нельзя выполнять привычку реже чем 1 раз в 7 дней')], verbose_name='Периодичность (в днях)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки (1-120 минут)', validators=[django.core.validators.MinValueValidator(1, message='Время выполнения должно быть не менее 1 минуты'), django.core.validators.MaxValueValidator(120, message='Время выполнения не должно превышать 120 минут')], verbose_name='Время на выполнение (в минутах)'),
        ),
    ]
