# Generated by Django 5.2.1 on 2025-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_periodicity_habit_periodicity_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=2025, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
