# Generated by Django 5.2.1 on 2025-06-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
    ]
